### ISSUE TITLE
Contrast suggestion

### ISSUE THREAD

**Issue by oblitum** [co1ncidence/gunmetal.vim#8]
I'm looking at your colorschemes and they look great, can I suggest something? Even though I think they're great at the moment I'm not picking them because I'm still in an endless search for a very dark colorscheme, but with low constrast, your colorschemes are almost there for me, except the foreground color is too bright. So I just wished to leave this suggestion.

I'm looking for that because I'm reading/coding in a very dark environment and most dark colorschemes have bright foreground, none seems to focus this usecase of wishing to have low light emission, even when the screen is full of text.

**Comment by co1ncidence** [comment]
I totally understand where you are coming from, just edit the `gunmetal.vim` files and go a find and replace for `#f0f0f0` and substiture with whatever color you'd like, personally, I would recommend `#e7e7e7` or `#dedede`, but it's all up to you. I've made the theme very edit-friendly as well, so you should have no problem tuning it to your preferences.

If what I've said is in any way confusing, please let me know, I'd be glad to clear things up!

**Comment by oblitum** [comment]
Thx, will try that. I also tried Mountaineer, it's nice too, just want to say there's an issue with lightline theme there, it's placed in the wrong dir, so lightline can't load it. it should be at `autoload/lightline/colorscheme/`, not at `autoload/lightline/`.
